apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "artemis.fullname" . }}
  labels:
    {{- include "artemis.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.artemis.replicaCount }}
  selector:
    matchLabels:
      {{- include "artemis.selectorLabels" . | nindent 6 }}

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate

  template:
    metadata:
      {{- with .Values.artemis.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "artemis.selectorLabels" . | nindent 8 }}
    spec:
      securityContext: {}
      restartPolicy: Always
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.artemis.image.repository }}{{ .Values.artemis.image.name }}:{{ .Values.artemisVersion | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.artemis.image.pullPolicy }}

          envFrom:
            - configMapRef:
                name: artemis-usermanagement-configmap
            - configMapRef:
                name: artemis-vcs-configmap
            - configMapRef:
                name: artemis-ci-configmap
            - configMapRef:
                name: artemis-app
                optional: false
            - configMapRef:
                name: application-config
                optional: false
            - secretRef:
                name: artemis-usermanagement-secrets
            - secretRef:
                name: artemis-vcs-secrets
            - secretRef:
                name: artemis-ci-secrets
            - secretRef:
                name: artemis-secrets
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          securityContext:
            {{- toYaml .Values.artemis.podSecurityContext | nindent 14 }}
          resources:
            {{- toYaml .Values.artemis.resources | nindent 12 }}
          volumeMounts:
            - mountPath: {{ .Values.artemis.volumes.mountPath }} 
              name: artemis-volume

      {{- with .Values.artemis.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.artemis.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.artemis.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      initContainers:
        - name: init-ds
          image: busybox:latest
          command:
              - '/bin/sh'
              - '-c'
              - |
                  while true
                  do
                    rt=$(nc -z -w 1 artemis-mysql 3306)
                    if [ $? -eq 0 ]; then
                      echo "DB is UP"
                      break
                    fi
                    echo "DB is not yet reachable;sleep for 10s before retry"
                    sleep 10
                  done

      volumes:
      - name: artemis-volume
        persistentVolumeClaim:
          claimName: {{ .Values.artemis.volumes.name }}
