apiVersion: v1
kind: Secret
metadata:
  name: artemis-ci-secrets
type: Opaque
data:
  {{- if eq .Values.application.continuousIntegration.provider "bamboo" }}
  artemis.continuous-integration.user: {{ required "Jira username is required" .Values.application.userManagement.jira.username | b64enc | quote }}
  artemis.continuous-integration.password: {{ required "Jira password is required" .Values.application.userManagement.jira.password | b64enc | quote }}
  artemis.continuous-integration.token: {{ required "Bamboo access token is required" .Values.application.continuousIntegration.bamboo.accessToken | b64enc | quote }}
  artemis.continuous-integration.artemis-authentication-token-value: {{ required "Bamboo notification token is required" .Values.application.continuousIntegration.bamboo.notificationToken | b64enc | quote }}
  {{- end }}
