apiVersion: v1
kind: Secret
metadata:
  name: artemis-secrets
type: Opaque
data:
  artemis.user-management.ldap.password: ""
  artemis.version-control.password: ""
  artemis.version-control.token: ""
  artemis.athene.base64-secret: ""
  artemis.continuous-integration.password: ""
  artemis.continuous-integration.token: ""
  artemis.lti.oauth-key: ""
  artemis.lti.oauth-secret: ""
