apiVersion: v1
kind: Secret
metadata:
  name: artemis-secrets
type: Opaque
data:
  artemis.user-management.ldap.password: ""
  artemis.athene.base64-secret: ""
  artemis.lti.oauth-key: ""
  artemis.lti.oauth-secret: ""
  jhipster.registry.password: {{ required "Registry  password is required" .Values.application.registry.password | b64enc | quote }}
  spring.security.user.password: {{ required "Registry  password is required" .Values.application.registry.password | b64enc | quote }}
  spring.security.websocket.broker.username: {{ required "Broker user is required!" .Values.application.broker.username | b64enc | quote }}
  spring.security.websocket.broker.password: {{ required "Broker password is required!" .Values.application.broker.password | b64enc | quote }}
