apiVersion: v1
kind: Secret
metadata:
  name: artemis-usermanagement-secrets
type: Opaque
data:
  {{- if and .Values.application.userManagement.useExternal ( eq .Values.application.userManagement.provider "jira") }}
  artemis.user-management.external.user: {{ required "Jira username is required" .Values.application.userManagement.jira.username | b64enc | quote }}
  artemis.user-management.external.password: {{ required "Jira password is required" .Values.application.userManagement.jira.password | b64enc | quote }}
  {{- end }}
  artemis.user-management.internal-admin.username: {{ required "Internal admin username is required!" .Values.application.userManagement.internalAdmin.username | b64enc | quote }}
  artemis.user-management.internal-admin.password: {{ required "Internal admin password is required!" .Values.application.userManagement.internalAdmin.password | b64enc | quote }}
