apiVersion: v1
kind: Secret
metadata:
  name: artemis-vcs-secrets
type: Opaque
data:
  {{- if eq .Values.application.versioncontrol.provider "bitbucket" }}
  artemis.version-control.user: {{ required "Jira username is required" .Values.application.userManagement.jira.username | b64enc | quote }}
  artemis.version-control.password: {{ required "Jira password is required" .Values.application.userManagement.jira.password | b64enc | quote }}
  artemis.version-control.token: {{ required "Bitbucket token is required" .Values.application.versioncontrol.bitbucket.token | b64enc | quote }}
  {{- end }}
