apiVersion: v1
kind: Secret
metadata:
  name: artemis-secrets
type: Opaque
data:
  artemis.athene.base64-secret: ""
  artemis.continuous-integration.password: ""
  artemis.continuous-integration.token: ""
  artemis.lti.oauth-key: ""
  artemis.lti.oauth-secret: ""
  artemis.user-management.external.password: ""
  artemis.user-management.internal-admin.username: {{ required "Interal admin username is required!" .Values.application.userManagement.internalAdmin.username }}
  artemis.user-management.internal-admin.password: {{ required "Interal admin password is required!" .Values.application.userManagement.internalAdmin.password }}
  artemis.user-management.ldap.password: ""
  artemis.version-control.password: ""
  artemis.version-control.token: ""
