apiVersion: v1
kind: ConfigMap
metadata:
  name: artemis-vcs-configmap
data:
  {{- if eq .Values.application.versioncontrol.provider "bitbucket" }}
  artemis.version-control.url: {{ required "Bitbucket url is required" .Values.application.versioncontrol.bitbucket.url | quote }}
  artemis.version-control.ssh-template-clone-url: {{ .Values.application.versioncontrol.bitbucket.sshCloneUrl | quote }}
  {{- end }}
