apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artemis-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.volumes.size }}
  {{- if eq .Values.database.volumes.storageClassName "" }}
  storageClassName: {{ .Values.database.volumes.storageClassName }}
  {{- end }}
  volumeMode: Filesystem
