apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.artemis.volumes.name }}
spec:
  {{- with .Values.artemis.volumes.accessModes }}
  accessModes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.artemis.volumes.size }}
  storageClassName: longhorn
  volumeMode: Filesystem
