apiVersion: v1
kind: Service
metadata:
  name: {{ include "artemis.fullname" . }}
  labels:
    {{- include "artemis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.artemis.service.type }}
  ports:
    - port: {{ .Values.artemis.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "artemis.selectorLabels" . | nindent 4 }}
