{{- if .Values.artemis.autoscaler.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "artemis.fullname" . }}
  labels:
    {{- include "artemis.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "artemis.fullname" . }}
  minReplicas: {{ .Values.artemis.autoscaler.minReplicas }}
  maxReplicas: {{ .Values.artemis.autoscaler.maxReplicas }}
  {{- with .Values.artemis.autoscaler.behavior }}
  behavior:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  metrics:
  {{- if .Values.artemis.autoscaler.metrics.usersPerInstance }}
  - type: Pods
    pods:
      metric:
        name: artemis_instance_websocket_users
      target:
        type: AverageValue
        averageValue: {{ .Values.artemis.autoscaler.metrics.usersPerInstance }}
  {{- end }}
{{- end }}