name: Build and Push Helm Chart

on:
  push:
    branches:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.15.0

      - name: Get branch name
        id: branch
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Update chart dependencies
        run: helm dependency update artemis

      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.3.0
        with:
          name: artemis
          repository: ls1intum/artemis-helm
          tag: 0.1.2-${{ env.BRANCH_NAME }}
          path: artemis
          registry: ghcr.io
          registry_username: ${{ github.repository_owner }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          update_dependencies: 'true'
